apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - fluent-bit-ds.yaml
  - fluent-bit-role-binding.yaml
  - fluent-bit-role.yaml
  - fluent-bit-service-account.yaml

configMapGenerator:
- name: fluent-bit-config
  files:
  - config/filter-kubernetes.conf
  - config/fluent-bit.conf
  - config/input-kubernetes.conf
  - config/output-elasticsearch.conf
  - config/parsers.conf
